#ifndef _KERNEL_CONFIG_H_
#define _KERNEL_CONFIG_H_

#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10

#define IDT_MAX_ENTRIES 0x100
#define IDT_CPU_EXCEPTION_ENTRIES 0x20

#define IDT_IRQ_ENTRIES 0x10
#define IDT_IRQ_STARTING_INTERRUPT_NUMBER 0x20
#define IDT_IRQ_END_INTERRUPT_NUMBER 0x30

/* Interrupt numbers are free from this point */
#define IDT_FREE_STARTING_INTERRUPT_NUMBER 0x30

/* Heap - 100MB Heap size. */

#define HEAP_MAX_HEAP_SIZE 104857600U
#define HEAP_MAX_HEAP_BLOCKS_ENTRIES 25600U
#define HEAP_BLOCK_SIZE 4096U

#define HEAP_BASE_ADDRESS 0x01000000
#define HEAP_TABLE_ADDRESS 0x00007E00

// Disk
// These both define the same thing.
#define _DISK_FS_SIZE 0x200U
#define _DISK_SECTOR_SIZE 0x200U

// File system
#define MAX_FILESYSTEMS 12U
#define MAX_FILE_DESCRIPTORS_ACTIVE 512U

#define _FS_MAX_PATH_LEN 108U
#define _FS_NULL_ADDRESS 0x00UL

#endif