#ifndef _KERNEL_CONFIG_H_
#define _KERNEL_CONFIG_H_

#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10

#define IDT_MAX_ENTRIES 0x100
#define IDT_CPU_EXCEPTION_ENTRIES 0x20

#define IDT_IRQ_ENTRIES 0x10
#define IDT_IRQ_STARTING_INTERRUPT_NUMBER 0x20
#define IDT_IRQ_END_INTERRUPT_NUMBER 0x30

/* Interrupt numbers are free from this point */
#define IDT_FREE_STARTING_INTERRUPT_NUMBER 0x30

/* Interrupts */
#define BasicOS_MAX_SYSCALL_HANDLE_COMMANDS 0x400U

/* GDT */
#define BasicOS_TOTAL_GDT_SEGMENTS 0x06U

/* Heap - 100MB Heap size. */

#define HEAP_MAX_HEAP_SIZE 104857600U
#define HEAP_MAX_HEAP_BLOCKS_ENTRIES 25600U
#define HEAP_BLOCK_SIZE 4096U

#define HEAP_BASE_ADDRESS 0x01000000
#define HEAP_TABLE_ADDRESS 0x00007E00

// Disk
// These both define the same thing.
#define _DISK_FS_SIZE 0x200U
#define _DISK_SECTOR_SIZE 0x200U

// File system
#define MAX_FILESYSTEMS 12U
#define MAX_FILE_DESCRIPTORS_ACTIVE 512U

#define _FS_MAX_PATH_LEN 108U
#define _FS_NULL_ADDRESS 0x00UL

/* Tasks */
#define BKE_TASK_PROGRAM_VIRTUAL_ADDR 0x400000U
// 16 KB
#define BKE_TASK_USER_DATA_SEGMENT 0x23U
#define BKE_TASK_USER_CODE_SEGMENT 0x1BU
#define BKE_TASK_USER_STACK_SIZE 0x4000U
#define BKE_TASK_PROGRAM_VIRTUAL_STACK_ADDR_START 0x3FF000U
#define BKE_TASK_PROGRAM_VIRTUAL_STACK_ADDR_END BKE_TASK_PROGRAM_VIRTUAL_STACK_ADDR_START - BKE_TASK_USER_STACK_SIZE

/* Process */
#define BasicOS_MAX_ALLOCATIONS_ALLOWED_PER_PROCESS 0x400U
#define BasicOS_MAX_PROCESSES 0xCU

/* Keyboard */
#define BasicOS_KEYBOARD_BUFFER_SIZE 0x400

#endif