#ifndef _KERNEL_CONFIG_H_
#define _KERNEL_CONFIG_H_

#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10

#define IDT_MAX_ENTRIES 0x100
#define IDT_CPU_EXCEPTION_ENTRIES 0x20

#define IDT_IRQ_ENTRIES 0x10
#define IDT_IRQ_STARTING_INTERRUPT_NUMBER 0x20
#define IDT_IRQ_END_INTERRUPT_NUMBER 0x30

/* Interrupt numbers are free from this point */
#define IDT_FREE_STARTING_INTERRUPT_NUMBER 0x30

#endif