#ifndef KERNEL_INTERRUPTS_ISR80H_H
#define KERNEL_INTERRUPTS_ISR80H_H

enum SYSCALL_IDS {
    SYS_SUM,
    SYS_PRINT,
    SYS_PRINT_EXT,
    SYS_GET_KET,
    SYS_PUT_CHAR,
    SYS_MALLOC,
    SYS_FREE,
    SYS_PROCESS_LOAD_START,
    SYS_INVOKE_SYS_COMMAND,
    SYS_GET_PROCESS_ARGUMENTS,
};

void isr80h_register_commands(void);

#endif